@startuml None
'GospelLibrary class
'Attributes:
GospelLibrary : -_bibleDictionary: Dictionary<string, string>
GospelLibrary : -_selectedScripture: string
GospelLibrary : -_keyLibrary: List<string>
GospelLibrary : -_selectedKeyIndex: int

'Constructors:
GospelLibrary : +GospelLibrary()
GospelLibrary : +GospelLibrary(Scripture: string)

'Methods
GospelLibrary : +StockScriptureDictionary(): void
GospelLibrary : +RandomKey(): void
GospelLibrary : +GetScripture(): string



'Scripture class
'Attributes:
Scripture : -_scripture: string
Scripture : -_modifiedScriptureText: List<string>
Scripture : -_wordsOfTheLivingProphets: List<string>

'Constructors:
Scripture : +ScritpureMastery(ChosenScripture: string)

'Methods:
Scripture : +SplitStringToWords(): void
Scripture : +ReplaceChosenWord(): void
Scripture : +GetWordCount(): int
Scripture : +PrintScripture()


'Reference class
'Attributes:
Reference : -_scriptureReference: string
Reference : -_hiddenReference: string
Reference : -_hideReference: bool

'Constructors:
Reference : +Reference(ScriptureReference)

'Methods:
Reference : +GetReferenceStatus(): void
' Reference : +HideReference(ReferenceIsHidden: bool): void
Reference : +PrintReference(): void



'Word class
'Attributes:
Word : -_wordPosition: int

'constructors:
Word : +Word()

'Methods:
Word : +RandomlySelectedHiddenWord(ListLength: int): void
Word : +ReturnHiddenWordIndex(): int
' Word : +SetWordStatus(): void



'Word2 class
'Attributes
Word2 : -_hiddenStatus: bool
Word2 : -_wordText: string

'Constructors:
Word2 : +Word2()
Word2 : +Word2(word: string)

'Methods:
Word2 : +ObtainHiddenStatus(): void
Word2 : +ReturnHiddenWord(): string
@enduml
